### ISSUE TITLE
Please repair your code...

### ISSUE THREAD

**Issue by EnthusiasticPurpleSoapMonger** [Fonta22/tdr-app#1]
Wassup man, i was scrolling thrugh codes while taking shower, and i got to dis one, and DAAAAMN man, how can you do it lik this, why can't i get my nMilky Ways chocolate bar from it?  Wit nowadays standerts someone's gott to reper it man! Not cool, man, not clol!
![7055916_preview](https://user-images.githubusercontent.com/114698828/193136415-32291560-7dbe-46cf-a520-76931225f76b.png)

**Comment by Fonta22** [comment]
Take milky way.
![image](https://user-images.githubusercontent.com/61181201/193213754-c747b1af-5dc7-4d44-b011-a25fcefb919e.png)

**Comment by Fonta22** [comment]
Also,
![image](https://user-images.githubusercontent.com/61181201/193254371-a01c18b3-a75e-4bb4-8674-22c320c1827f.png)
