### ISSUE TITLE
:|

### ISSUE THREAD

**Issue by ElonMuskCEOofTesla** [Fonta22/tdr-app#4]
BOO!

**Comment by Fonta22** [comment]
EEEEEEEE.
Chill man! I didn't steal your logo...

Check this:
![image](https://user-images.githubusercontent.com/61181201/193469140-4f1c00b3-683c-4ef8-87c5-872965e46cd2.png)

**Comment by ElonMuskCEOofTesla** [comment]
![Map-of-Europe-showing-names-of-countries-which-have-member-agencies-in-EuroGOOS-and-the](https://user-images.githubusercontent.com/114876774/193469280-b648bcde-4ea2-4245-b500-8604d8fe0b48.png)

**Comment by ElonMuskCEOofTesla** [comment]
i know... where the France is

**Comment by Fonta22** [comment]
What are you trying to say? ...

**Comment by ElonMuskCEOofTesla** [comment]
there is a sneaky monkey... under my armpit... he are very soft and hungry... please unlock your front door

**Comment by ElonMuskCEOofTesla** [comment]
![download png](https://user-images.githubusercontent.com/114876774/193470336-4a9d32a3-b895-4539-a8ac-9364240c2dd2.png)

**Comment by Fonta22** [comment]
![image](https://user-images.githubusercontent.com/61181201/193475644-d7a24350-0b37-4bf1-ba68-ad47967cf103.png)

**Comment by Fonta22** [comment]
Skype monke
